baseURL = "https://john.lgbt"
theme = "hugo-bearblog"

title = "John's Creative Relationship Space"
author = "masculine@john.lgbt"
copyright = "CC BY-SA 4.0"
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = false

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  # The "description" of your website. This is used in the meta data of your generated html.
  title = "JCRS"
  description = "Taking our environment by the steering wheeel. ðŸ’œ"
  favicon = "static/favicon.ico"

  # images = ["images/social-graphic.png"]
  hideMadeWithLine = true
  enablePostNavigator = true
  dateFormat = "Mon Jan 2 06"

# Configure markup highlighter to match "Bearblog" aesthetics
# see https://gohugo.io/configuration/markup/#highlight
[markup]
  [markup.highlight]
    style = 'friendly'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  page = ["HTML"]
