baseURL = "https://john.lgbt"
theme = "hugo-bearblog"

title = ""
author = "masculine@john.lgbt"
copyright = "CC BY-SA 4.0"
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = false

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  title = "JCRS"
  description = "Taking our environment by the steering wheeel. ðŸ’œ"
  favicon = "favicon.ico"
  images = ["tricky-canon.jpg"]
  
  hideMadeWithLine = true
  enablePostNavigator = true
  dateFormat = "Mon Jan 2 06"
  mainSections = ["blog"]


# Configure markup highlighter to match "Bearblog" aesthetics
# see https://gohugo.io/configuration/markup/#highlight
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'friendly'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  page = ["HTML"]
